name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy;
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
